### ISSUE TITLE
Feature request: Add logging context to a logger instance or code scope

### ISSUE THREAD

**Issue by SweVictor** [jonwagner/EventSourceProxy#25]
Firstly: Great work and extremely useful to quickly implement an eventsource!

Secondly: I hope it's ok to post requests here and not only problems...

So: We have started using EventSourceProxy heavily and really enjoy the way everything is laid out. We have one request though: To be able to add context to a logging instance or to a scope of code. In our case we one process handling multiple objects, each with its own id and metadata. We would like to decorate each request with that id and metadata to make correlating logs easier. What we would like to achieve is something like this:

```
for (var specificObject in hander.specificObjects) {
  //The initialization would of course be done early to reuse the instance
  var log = EventSourceImplementer.GetEventSourceAs<IMyLogger>();
  log.ForAnything()
        .AddContext("specificObject", () => new {id = specificObject.Id, name = specificObject.Name};

  //Do stuff and log data!
}
```

or, with scoping, something like

```
var log = EventSourceImplementer.GetEventSourceAs<IMyLogger>();
for (var specificObject in hander.specificObjects) {
  using (log.ForAnything()
        .AddContext("specificObject", () => new {id = specificObject.Id, name = specificObject.Name};
  ) {
    //Do stuff and log data!
  }
}
```

In our use case, the first version would be the most preferred one, but both would make a nice improvement compared to adding the metadata to each request. Also it would be nice if keywords/tasks/opcodes could be added or log levels could be adjusted on a per call or per instance level.

Would something like this be feasible to implement?

Thanks in advance!
/Victor

**Comment by jonwagner** [comment]
It's not done yet. :(

**Comment by jonwagner** [comment]
I just can't leave a problem unsolved. Adding this feature to v3.0.5!

You can now use AddContextData when configuring the TraceParameterProvider. It will look up data stored in the TraceContext context bag, which you can define with TraceContext.Begin(). Example below!

			TraceParameterProvider.Default.For<IHaveRichContext>()
				.AddContextData("Site.Id")
				.AddContextData("Site.Name")
				.AddContextData("PID");

			var proxy = EventSourceImplementer.GetEventSourceAs<IHaveRichContext>();

			using (var context = TraceContext.Begin())
			{
				context["PID"] = 1234;

				using (var context2 = TraceContext.Begin())
				{
					context2["Site.Id"] = "Ts1";
					context2["Site.Name"] = "TestSite1";

					proxy.Log("message");
				}
			}

**Comment by SweVictor** [comment]
Really great to see this implemented, we will for sure use this in the future to remove the need of adding context with every call - fantastic!

**Comment by jonwagner** [comment]
Just pushed v3.0.5 with this code in it.
