### ISSUE TITLE
NuGet -> Futures?

### ISSUE THREAD

**Issue by Michael-DST** [jonwagner/EventSourceProxy#31]
Just a thought here.  I am thinking it would be better to name "NuGet" to "Futures", as that is what the Microsoft.Diagnostics.Tracing.EventSource is.  If interested, I have a commit here:
https://github.com/Michael-DST/EventSourceProxy/commit/2767ab4e12abaa6fc77586ecf73f8397848e8792

I also made an improvement with how the files are namespaced.  That is, there were ifdefs around the namespace (EventSourceProxy.NuGet), when the namespace can be just the same as the "Present" assembly (EventSourceProxy).

Obviously, this is a breaking change for current code... and would be something to consider for future version.

I can send a pull request if you'd like.  No worries if not, otherwise.  Just a thought/suggestion. :)

**Comment by jonwagner** [comment]
I merged your code changes in, but I didn't rename the package. I'm not sure how to redirect the packages in NuGet. (I'm also wary of calling it "Futures", since everything seems to be going in NuGet now.)
