### ISSUE TITLE
Enum type ToString in TraceParameterProvider

### ISSUE THREAD

**Issue by megakid** [jonwagner/EventSourceProxy#33]
Hi there,

I have been logging my events using an interface that EventSourceProxy enables.  E.g.

    [EventSourceImplementation(Name = "MySource")]
    public interface IEventSource
    {
        [Event(1, Level = EventLevel.Informational)]
        void LogItServiceStatusEvent(string itService, RagStatus status);
     }

This works fine but the event has 'status' = 0, 1, 2 etc... corresponding to the enum value.  I want to print the name of the enum value instead.  Following the documentation, I added this line before any proxies are created:

                TraceParameterProvider.Default.ForAnything()
                    .With<RagStatus>().Trace(e => e.ToString()).As("status");

Now I get this error when creating my proxy:

A first chance exception of type 'System.InvalidOperationException' occurred in EventSourceProxy.dll

Additional information: Cannot convert type ChamMon.Model.RagStatus to a type compatible with EventSource

My other remapped properties work fine.  Is there another way of achieving my goal?

Cheers,

James

**Comment by jonwagner** [comment]
This is fixed in v3.0.4. For my tests, I configured it as:

    TraceParameterProvider.Default.ForAnything().Trace((RagStatus s) => s.ToString());
