### ISSUE TITLE
[Query] How to use TracingProxy to write into Windows event log using the EventSourceProxy.NuGet namespace

### ISSUE THREAD

**Issue by samarthraman** [jonwagner/EventSourceProxy#34]
I am trying to implement tracing for an existing code base and came across the EventSourceProxy. By using the TracingProxy class, I am able to inject tracing and the required method data shows up properly when I use logman/perfview combo. Now what I am trying to do is to have these events publish to the event log and based on the thread here (https://github.com/jonwagner/EventSourceProxy/issues/15), I switched to using the EventSourceProxy.NuGet namespace but I am unable to get the events publish to event log

I tried registering the event by creating the manifest and see the entry under the "Application and service logs" in EventViewer but there were no events captured. I even tried overriding the default implementation in the EventAttributeProvider class and default the channel attribute to Admin. The thing that I think might be missing is the manifest.dll class that is required as the resource file and message file as part of manifest installaton.

Any help on this will be greatly appreciated. Thanks

**Comment by jonwagner** [comment]
I haven't tried getting ESP events into the EventLog. I'll have to find some time to try it out.

**Comment by samarthraman** [comment]
Looking forward to it, thanks a lot Jon.

**Comment by jonwagner** [comment]
Sorry it took so long to get back to this.

You can get the manifest from the GenerateProxyManifest tool. You don't need the DLL unless you're localizing resources.

Instructions are in the wiki:

https://github.com/jonwagner/EventSourceProxy/wiki/Getting-the-EventSource-Manifest-or-GUID
