### ISSUE TITLE
Change the name of TracingProxy generated EventSource

### ISSUE THREAD

**Issue by ibebbs** [jonwagner/EventSourceProxy#35]
Hi John,

Still loving EventSourceProxy; I'm using it all over the place.

One question, is it possible to change the event source name of an event source generated by the TracingProxy? Ideally something along the lines of ```[EventSourceImplementation(Name = "<name>")]``` but without having to attribute the interface being proxied (i.e. if it is from a third party).

Something along the lines of: ```TracingProxy.CreateWithActivityScope<ICalculator>(new Calculator(), "MyProxiedCalculator")``` (where 'MyProxiedCalculator' is the new event source name) would be great.

Cheers,
  Ian

**Comment by jonwagner** [comment]
That probably wouldn't be too hard.

One thing you ca try right now is deriving your own interface:

    [attribute] interface IMyInterface : ITheirInterface {}

If the interface isn't sealed, this will probably work for you.

**Comment by ibebbs** [comment]
Ha, cunning. Yes, that'd work but does increase the ceremony around it.

I'll have a look at running with that for now.

Cheers Jon.

**Comment by jonwagner** [comment]
In v3.0.4, you can now do:

	EventSourceImplementationAttribute.For<IHateThisName>(new EventSourceImplementationAttribute() { Name = "A Better Name" });

**Comment by ibebbs** [comment]
Looks great Jon. I'll give it a shot when I get back to work!
