### ISSUE TITLE
How to get the manifest?

### ISSUE THREAD

**Issue by alphaleonis** [jonwagner/EventSourceProxy#41]
Maybe I'm missing something here, but I've been using the NuGet package of the EventSource to have a manifest automatically generated at build time, since I need this installed with my product.
Using the EventSourceProxy would definitely simplify writing and maintaining the EventSource classes, but how can I get the manifest generation to work? 

If I create an abstract class, with abstract event methods and decorate them with the `EventAttribute` to specify channels, opcodes, tasks and keywords, I get a build error saying that an abstract class cannot have event methods. 

So how can I get around this? Is there any way to have the manifest generated from the class that EventSourceProxy generates?

**Comment by jonwagner** [comment]
https://github.com/jonwagner/EventSourceProxy/wiki/Getting-the-EventSource-Manifest-or-GUID

way ahead of you
