### ISSUE TITLE
EventSourceProxy for .NET 3.5 or 4.0

### ISSUE THREAD

**Issue by g-mack** [jonwagner/EventSourceProxy#44]
Hi,

I really like the idea of using EventSource and Semantic Logging in my C# projects and this EventSourceProxy project is a brilliant implementation which would help a lot and take away this tedious typing of the EventSource class.
Sadly most of my customers (client applications...) are not fully updated to .NET 4.5 Framework.
So I used the EventSource from the Microsoft namespace to get this working in previous versions.

Sadly your EventSourceProxy.Nuget package is targeting .NET Framework 4.5.
Is there a version planned/ implemented for .NET Frameworks prior to 4.5?

I hope this "issue" is the right way to ask this questions, otherwise I apologize for that, as I´m a new member to github...

Thanks and go on with that project! 

Gerhard Mack

**Comment by jonwagner** [comment]
I'd love to be able to support older versions, but I don't think I'll find the time in the near future. I'd be happy to accept pull requests!

**Comment by jonwagner** [comment]
Moving forward, this project will support net46 and netstandard2.0
