### ISSUE TITLE
EventSourceImplementationAttribute should not be sealed

### ISSUE THREAD

**Issue by oocx** [jonwagner/EventSourceProxy#45]
I'm currently working on some base logging classes and guidelines for about 25 developers. We are considering to use ETW based logging with EventSourceProxy. We try to reduce the complexity and the many choices that ETW offers by providing base classes that our developers can use.

It would be nice if we could create our own attribute that inherits from EventSourceImplementationAttribute. This would allow us to set some defaults or hide some of the settings that are available on that attribute (if they see all the properties that EventSourceImplementationAttribute offers, I would need to explain how to use them and which of these properties need to be specified).

**Comment by jonwagner** [comment]
Unsealed in 4.0.0.
