### ISSUE TITLE
using newer versions of the Microsoft EventSource NuGet package throws FileLoadException

### ISSUE THREAD

**Issue by oocx** [jonwagner/EventSourceProxy#46]
When I try to use a newer version of the Microsoft EventSource NuGet package, EventSourceProxy fails with a FileLoadException. As a workaround, I need to manually add assembly binding redirects to all applications where I use EventSourceProxy.

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Diagnostics.Tracing.EventSo
urce, Version=1.0.16.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assemb
ly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at EventSourceProxy.NuGet.EventSourceManifest.GenerateManifest(Type type)
   at GenerateProxyManifest.Program.GenerateManifest(String assemblyPath, String typeName)
   at GenerateProxyManifest.Program.Main(String[] args)

**Comment by Benjol** [comment]
I got this also, but only for the case where I was trying to extract the manifest using the GenerateProxyManifest tool.

**Comment by jonwagner** [comment]
Closing due to the age of the bug. Feel free to reopen when 4.0.0 is released.
