### ISSUE TITLE
setup continuous integration build

### ISSUE THREAD

**Issue by oocx** [jonwagner/EventSourceProxy#50]
You should add a CI build to automatically build and run tests on checkins and pull requests.

I'm using AppVeyor for my own project. It's free and has a great GitHub integration. I can help you with the configuration if you want.

I have set up an AppVeyor build for my own EventSourceProxy fork. If you want to use that, you only need to configure WebHooks so that GitHub notifies AppVeyor about new checkins. The Webhook URL for that would be: https://ci.appveyor.com/api/github/webhook?id=pq6y4k2qtrb968ca

The AppVeyor project is here: https://ci.appveyor.com/project/oocx/eventsourceproxy

**Comment by jonwagner** [comment]
Closing for now.
