### ISSUE TITLE
Support for Func-Parameter

### ISSUE THREAD

**Issue by mjeanrichard** [jonwagner/EventSourceProxy#54]
It would be very nice if I could pass a `Func<string>` to a log method which would only be evaluated (and logged) when the Event is enabled.
Is this already possible? If not, could this feature be added?

Thanks a lot for your great work!

**Comment by jonwagner** [comment]
I'm not totally sure how this is different from the trace parameter providers, but let me know and I'll add to it. I'll be releasing version 4.0.0 shortly.
