### ISSUE TITLE
What is the future of EventSource?

### ISSUE THREAD

**Issue by gsteinbacher** [jonwagner/EventSourceProxy#58]
I am a huge fan of EventSource (and EventSourceProxy by proxy :)) but I have noticed that due to the Dependency Injection pattern in ASP.Net Core the EventSource does not easily fit into this paradigm.   We will be doing a majority of our future development in ASP.Net Core.

Do you know what the future of EventSource is?  Do you think Microsoft will continue to support this as a first class citizen or should I start looking to use another logger?

**Comment by bdongus** [comment]
Maybe this helps: [ETW in vNext](http://patrickdesjardins.com/blog/tracing-with-event-tracing-for-windows-etw-an-asp-net-vnext)

**Comment by jonwagner** [comment]
It looks like EventSource is fully supported in .NET standard 2.0 and future versions.

I was able to update ESP to work with it. Follow the updates in #59 !
